# Generated by Django 4.2.27 on 2026-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stockprice_alter_targetallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
